[build-system]
requires = [
    "setuptools", "wheel", "cython",
]


[project.optional-dependencies]
doc = [
    "sphinx-copybutton",
    "sphinx_rtd_theme",
    "sphinx",
    "cython"
]

test = [
  "pytest"
]
